server:
  port: 9090
  servlet.context-path: /ms-mcms
  servlet.session.timeout: 60M
  
logging:
 level:
  net.mingsoft: trace
ms:
 manager: 
  path: /ms
  view-path: /WEB-INF/manager
  
 upload: 
   path: upload
   mapping: /upload/**
   denied: .exe,.jsp
   multipart:
     #最大上传文件大小 单位：KB
     max-file-size: 10240
     #文件暂存临时目录
     upload-temp-dir: temp
     #临时文件大小
     max-in-memory-size: 10240
     #总上传最大大小 单位：KB -1禁用
     max-request-size: -1





spring:
  profiles:
    active: dev
  mvc:
    pathmatch: 
     use-suffix-pattern: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 100MB
      enabled: false
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: classpath:/WEB-INF/manager,classpath:/WEB-INF
    settings: 
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      auto_import: /include/macro.ftl as ms
      number_format: 0.##
      
mybatis:
  mapper-locations: classpath*:**/dao/*.xml
  configuration: 
   database-id: mysql